version: '3'

services:
    app:
      links:
        - mail
      environment:
        TYPO3_CONTEXT: ${PROVISION_CONTEXT}/Docker

    mail:
       image: mailhog/mailhog
       ports:
         - ${EXTERNAL_MAIL_PORT}:8025
       container_name: ${COMPOSE_PROJECT_NAME}_mail