version: '3'

services:
    app:
      links:
        - mail
        - mysql
      environment:
        SYMFONY_ENV: dev
        SYMFONY_DEBUG: 1

  #######################################
  # MYSQL server
  #######################################
    mysql:
      build:
          context: mysql
          dockerfile: Dockerfile
          args:
            MYSQL_VERSION: ${MYSQL_VERSION}
      container_name: ${COMPOSE_PROJECT_NAME}_mysql
      environment:
          MYSQL_DATABASE: app_db
          MYSQL_USER: dev
          MYSQL_PASSWORD: dev
          MYSQL_ROOT_PASSWORD: dev
      ports:
        - ${EXTERNAL_DB_PORT}:3306
      volumes:
        - ./../data/mysql/:/var/lib/mysql:delegated

  #######################################
  # mailhog
  #######################################
    mail:
       image: mailhog/mailhog
       ports:
         - ${EXTERNAL_MAIL_PORT}:8025
       container_name: ${COMPOSE_PROJECT_NAME}_mail